encoding: utf-8

# SEO相关信息
title: 薅羊毛小分队-薅羊毛|活动线报|免费赚钱
description: 分享网赚线报,免费资源,免费会员账号和免费赚钱,免费活动,分享最新活动线报项目,有奖活动信息，而这一切都是免费分享给大家。
keywords: 微信线报,网赚,网上赚钱,百度网盘会员账号,爱奇艺会员账号,调查赚钱,网上兼职,薅羊毛,有奖活动,活动线报群
author: 薅羊毛小分队
footerText: 'Copyright © 2020'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'http://blog.tmaize.net'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/86335

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: false

# 百度收录自动推送,不需要请设置为false
extBaidu: true

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
  - title: 薅羊毛小分队
    url: https://yzcx.github.io
